config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :hours
  resources :corporation_types
  resources :corporation_users do
    collection do 
      get :create_corporation_user
      get :delete_corporation_user 
    end
  end 
  resources :process_depts do 
    collection do
      get :create_process
      get :edit_process
      get :delete_process
      get :get_process_by_corporation
      get :get_process_by_client
    end
  end
  resources :appointments do 
    collection do
      post :create_appointment
      post :list_appointment
      post :update_appointment
      post :disable_appointment
      get :register_appointment
      get :delete_appointment
      get :get_appointment
      get :export
    end
  end
  resources :projects do 
    collection do 
      get :get_clients
      get :get_corporations
      get :get_contracts_by_client
      get :get_areas_by_corporation
      get :get_areas_by_client
    end
  end
  resources :contracts
  resources :corporations do 
    collection do 
      get :index_clients
      get :index_companies
      get :get_users_by_corporation
    end
  end
  resources :areas do
    collection do
      get :get_areas_by_corporation
      get :create_area_exist_corporation
      get :get_areas_by_client
      get :create_area
      get :edit_area
      get :delete_area
    end
  end
  # devise_for :users

  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  get 'home/index'
  get 'home/index_company'
  get 'home/information'
  get 'home/not_found'
  get 'home/forbidden'


  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unnaceptable"
  get "/500", to: "errors#internal_error"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

end

app/controllers/corporation_types_controller.rb
class CorporationTypesController < ApplicationController
  before_action :set_corporation_type, only: [:show, :edit, :update, :destroy]

  # GET /corporation_types
  # GET /corporation_types.json
  def index
    @corporation_types = CorporationType.all
  end

  # GET /corporation_types/1
  # GET /corporation_types/1.json
  def show
  end

  # GET /corporation_types/new
  def new
    @corporation_type = CorporationType.new
  end

  # GET /corporation_types/1/edit
  def edit
  end

  # POST /corporation_types
  # POST /corporation_types.json
  def create
    @corporation_type = CorporationType.new(corporation_type_params)

    respond_to do |format|
      if @corporation_type.save
        format.html { redirect_to @corporation_type, notice: 'Corporation type was successfully created.' }
        format.json { render :show, status: :created, location: @corporation_type }
      else
        format.html { render :new }
        format.json { render json: @corporation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /corporation_types/1
  # PATCH/PUT /corporation_types/1.json
  def update
    respond_to do |format|
      if @corporation_type.update(corporation_type_params)
        format.html { redirect_to @corporation_type, notice: 'Corporation type was successfully updated.' }
        format.json { render :show, status: :ok, location: @corporation_type }
      else
        format.html { render :edit }
        format.json { render json: @corporation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corporation_types/1
  # DELETE /corporation_types/1.json
  def destroy
    @corporation_type.destroy
    respond_to do |format|
      format.html { redirect_to corporation_types_url, notice: 'Corporation type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_corporation_type
      @corporation_type = CorporationType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def corporation_type_params
      params.require(:corporation_type).permit(:name)
    end
end

app/helpers/corporation_types_helper.rb
module CorporationTypesHelper
end

app/views/corporation_types/_form.html.erb
<%= form_with(model: corporation_type, local: true) do |form| %>
  <% if corporation_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(corporation_type.errors.count, "error") %> prohibited this corporation_type from being saved:</h2>

      <ul>
      <% corporation_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :corporation_type_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/corporation_types/edit.html.erb
<h1>Editing Corporation_type</h1>

<%= render 'form', corporation_type: @corporation_type %>

<%= link_to 'Show', @corporation_type %> |
<%= link_to 'Back', corporation_types_path %>

app/views/corporation_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Corporation_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @corporation_types.each do |corporation_type| %>
      <tr>
        <td><%= corporation_type.name %></td>
        <td><%= link_to 'Show', corporation_type %></td>
        <td><%= link_to 'Edit', edit_corporation_type_path(corporation_type) %></td>
        <td><%= link_to 'Destroy', corporation_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Corporation_type', new_corporation_type_path %>

app/views/corporation_types/new.html.erb
<h1>New Corporation_type</h1>

<%= render 'form', corporation_type: @corporation_type %>

<%= link_to 'Back', corporation_types_path %>

app/views/corporation_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @corporation_type.name %>
</p>

<%= link_to 'Edit', edit_corporation_type_path(@corporation_type) %> |
<%= link_to 'Back', corporation_types_path %>