config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :hours
  resources :corporation_types
  resources :corporation_users do
    collection do 
      get :create_corporation_user
      get :delete_corporation_user 
    end
  end 
  resources :process_depts do 
    collection do
      get :create_process
      get :edit_process
      get :delete_process
      get :get_process_by_corporation
      get :get_process_by_client
    end
  end
  resources :appointments do 
    collection do
      post :create_appointment
      post :list_appointment
      post :update_appointment
      post :disable_appointment
      get :register_appointment
      get :delete_appointment
      get :get_appointment
      get :export
    end
  end
  resources :projects do 
    collection do 
      get :get_clients
      get :get_corporations
      get :get_contracts_by_client
      get :get_areas_by_corporation
      get :get_areas_by_client
    end
  end
  resources :contracts
  resources :corporations do 
    collection do 
      get :index_clients
      get :index_companies
      get :get_users_by_corporation
    end
  end
  resources :areas do
    collection do
      get :get_areas_by_corporation
      get :create_area_exist_corporation
      get :get_areas_by_client
      get :create_area
      get :edit_area
      get :delete_area
    end
  end
  # devise_for :users

  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  get 'home/index'
  get 'home/index_company'
  get 'home/information'
  get 'home/not_found'
  get 'home/forbidden'


  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unnaceptable"
  get "/500", to: "errors#internal_error"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

end

app/models/process_dept.rb
class ProcessDept < ApplicationRecord
  belongs_to :area

  has_many :appointments, dependent: :destroy
end

app/controllers/process_depts_controller.rb
class ProcessDeptsController < ApplicationController
  before_action :set_process_dept, only: [:show, :edit, :update, :destroy]

  def create_process
    process = ProcessDept.create(:name => params[:name], :area_id => params[:area_id])

    return render :json => process
  end

  def edit_process
    process = ProcessDept.where(id: params[:process_id]).update(:name => params[:name])

    return render :json => process
  end

  def delete_process
    process = ProcessDept.find(params[:id])
    process.destroy

    return render json: {}, status: 200
  end

  def get_process_by_corporation
    process = ProcessDept.find_by_sql("select distinct process_depts.* 
                                      from process_depts 
                                      inner join areas on process_depts.area_id in 
                                      (select areas.id from areas where corporation_id = #{params[:id]})
                                      order by id asc")

    return render :json => process
  end

  def get_process_by_client
    process = ProcessDept.find_by_sql("select distinct process_depts.* 
                                      from process_depts 
                                      inner join areas on process_depts.area_id in 
                                      (select areas.id from areas where client_id = #{params[:id]})
                                      order by id asc")

    return render :json => process
  end

  # GET /process_depts
  # GET /process_depts.json
  def index
    @process_depts = ProcessDept.all
  end

  # GET /process_depts/1
  # GET /process_depts/1.json
  def show
  end

  # GET /process_depts/new
  def new
    @process_dept = ProcessDept.new
  end

  # GET /process_depts/1/edit
  def edit
  end

  # POST /process_depts
  # POST /process_depts.json
  def create
    @process_dept = ProcessDept.new(process_dept_params)

    respond_to do |format|
      if @process_dept.save
        format.html { redirect_to @process_dept, notice: 'Process dept was successfully created.' }
        format.json { render :show, status: :created, location: @process_dept }
      else
        format.html { render :new }
        format.json { render json: @process_dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /process_depts/1
  # PATCH/PUT /process_depts/1.json
  def update
    respond_to do |format|
      if @process_dept.update(process_dept_params)
        format.html { redirect_to @process_dept, notice: 'Process dept was successfully updated.' }
        format.json { render :show, status: :ok, location: @process_dept }
      else
        format.html { render :edit }
        format.json { render json: @process_dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /process_depts/1
  # DELETE /process_depts/1.json
  def destroy
    @process_dept.destroy
    respond_to do |format|
      format.html { redirect_to edit_area_path(@process_dept.area_id), notice: 'Process dept was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_process_dept
      @process_dept = ProcessDept.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def process_dept_params
      params.require(:process_dept).permit(:area_id, :name)
    end
end

app/helpers/process_depts_helper.rb
module ProcessDeptsHelper
end

app/views/process_depts/_form.html.erb
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <ol class="breadcrumb">
      <li>
        <%= link_to root_path do %>Início<% end %>
      </li>
      <li class="active">
        <%= link_to process_depts_path do %>Processos<% end %>
      </li>
      <li class="active">
        Novo
      </li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <div class="card-box">
      <div class="row">
        <%= form_with(model: process_dept, local: true, :id => "form") do |form| %>
          <% if process_dept.errors.any? %>
            <div class="alert alert-danger" id="danger-alert">
              <button type="button" class="close" data-dismiss="alert">x</button>
              <strong>Erro! </strong>
              Por favor, preencha todos os campos obrigatórios
            </div>
          <% end %>
          
          <div class="p-20"> 
            <h4 class="m-t-0 header-title" style="text-align:center;"><b>INFORMAÇÕES DO PROCESSO</b></h4>
            <br> 
            <div class="form-group">
              <span>DEPARTAMENTO</span>
              <%= form.select(:area_id, Area.all.collect {|u| [u.name, u.id]}, {}, {class: "form-control select2"}) %>
            </div>
            <div class="form-group">
              <span>NOME</span>
              <%= form.text_field :name, id: :process_dept_name, class: "form-control", required:true, placeholder: "Nome" %> 
            </div>

            <div class="form-group" style="text-align:left;">
              <%= link_to process_depts_path do %>
                <button class="btn btn-white waves-effect waves-light">Voltar</button>
              <% end %>
              <button type="submit" class="btn btn-default waves-effect waves-light">Salvar</button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/process_depts/edit.html.erb
<h1>Editing Process_dept</h1>

<%= render 'form', process_dept: @process_dept %>

<%= link_to 'Show', @process_dept %> |
<%= link_to 'Back', process_depts_path %>

app/views/process_depts/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h4 class="page-title">Processos</h4>
    <ol class="breadcrumb">
      <li>
        <%= link_to root_path do %>Início<% end %>
      </li>
      <li class="active">
        Processos
      </li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class="card-box">
      <h4 class="m-t-0 header-title"><b></b></h4>
      <%= link_to new_process_dept_path, class: "btn btn-default btn-md waves-effect waves-light m-b-30" do %>
        Novo processo
      <% end %>

      <table data-toggle="table"
           data-show-columns="false"
           data-page-size="5"
           data-pagination="true" data-show-pagination-switch="true" class="table-bordered ">
        <thead>
          <tr>
            <th width="100">#</th>
            <th width="800">Nome</th>
            <th width="800">Área</th>
            <th width="10"></th>
          </tr>
        </thead>

        <tbody>
          <% @process_depts.each do |pd| %>
          <tr>
            <td width="100"><%= pd.id.to_s.rjust(3,'0') %></td>
            <td width="800"><%= pd.name %></td>
            <td width="800"><%= pd.area.name %></td>
            <td>
              <%= link_to '', edit_process_dept_path(pd), class: 'fa fa-pencil', title: 'Editar' %>
              <%= link_to '', pd, method: :delete, data: { confirm: 'Confirmar exclusão?' }, class: 'fa fa-trash-o', title: 'Excluir' %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/process_depts/new.html.erb
<%= render 'form', process_dept: @process_dept %>

app/views/process_depts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Area:</strong>
  <%= @process_dept.area %>
</p>

<p>
  <strong>Name:</strong>
  <%= @process_dept.name %>
</p>

<%= link_to 'Edit', edit_process_dept_path(@process_dept) %> |
<%= link_to 'Back', process_depts_path %>