config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :hours
  resources :corporation_types
  resources :corporation_users do
    collection do 
      get :create_corporation_user
      get :delete_corporation_user 
    end
  end 
  resources :process_depts do 
    collection do
      get :create_process
      get :edit_process
      get :delete_process
      get :get_process_by_corporation
      get :get_process_by_client
    end
  end
  resources :appointments do 
    collection do
      post :create_appointment
      post :list_appointment
      post :update_appointment
      post :disable_appointment
      get :register_appointment
      get :delete_appointment
      get :get_appointment
      get :export
    end
  end
  resources :projects do 
    collection do 
      get :get_clients
      get :get_corporations
      get :get_contracts_by_client
      get :get_areas_by_corporation
      get :get_areas_by_client
    end
  end
  resources :contracts
  resources :corporations do 
    collection do 
      get :index_clients
      get :index_companies
      get :get_users_by_corporation
    end
  end
  resources :areas do
    collection do
      get :get_areas_by_corporation
      get :create_area_exist_corporation
      get :get_areas_by_client
      get :create_area
      get :edit_area
      get :delete_area
    end
  end
  # devise_for :users

  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  get 'home/index'
  get 'home/index_company'
  get 'home/information'
  get 'home/not_found'
  get 'home/forbidden'


  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unnaceptable"
  get "/500", to: "errors#internal_error"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :contract, optional: true
	belongs_to :corporation, optional: true
	belongs_to :client, optional: true

	has_many :appointments, dependent: :destroy
	has_and_belongs_to_many :users
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  skip_authorize_resource :only => [:get_clients, :get_corporations, :get_contracts_by_client, 
                                    :get_areas_by_corporation, :get_areas_by_client, :new, :create]

  def get_clients
    @result = Corporation.joins(:corporation_users).where("corporation_users.user_id = #{User.current.id} and corporation_type_id = 1")
    respond_to do |format|
      format.json { render :json => @result }
    end
  end 

  def get_corporations
    @result = Corporation.joins(:corporation_users).where("corporation_users.user_id = #{User.current.id} and corporation_type_id = 2")

    respond_to do |format|
      format.json { render :json => @result }
    end
  end

  def get_contracts_by_client
    @result = Contract.where(client_id: params[:client])
    respond_to do |format|
      format.json { render :json => @result }
    end
  end

  def get_areas_by_corporation
    @result = Area.where(corporation_id: params[:client])
    respond_to do |format|
      format.json { render :json => @result }
    end
  end

  def get_areas_by_client
    @result = Area.where(client_id: params[:client])
    respond_to do |format|
      format.json { render :json => @result }
    end
  end

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.joins("left outer join clients on clients.id = projects.client_id")
                       .where("(projects.corporation_id in (
                              select corporation_id from corporation_users where user_id = #{User.current.id})
                              or
                              clients.corporation_id in (
                              select corporation_id from corporation_users where user_id = #{User.current.id}))")
    @corporations = Corporation.where("corporation_type_id = 2 and id in (select corporation_id from corporation_users where user_id = #{User.current.id})").count(:id)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_path, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :contract_id, :corporation_id, :type_project, :area_id, :sponsor, :manager, :objective, 
                                      :client_id, :start_date, :end_date, :estimate, :obs, :associate, :code, user_ids:[])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.erb
<style type="text/css">
  .last-collumn {
    width: 75px !important
  }
</style>

<div class="row">
  <div class="col-sm-12">
    <h4 class="page-title">Projetos</h4>
    <ol class="breadcrumb">
      <li>
        <%= link_to root_path do %>Início<% end %>
      </li>
      <li class="active">
        Projetos
      </li>
    </ol>
  </div>
</div>

<% if @corporations > 0 %>
  <div class="row">
    <div class="col-sm-12">
      <div class="card-box">
        <h4 class="m-t-0 header-title"><b></b></h4>
        <%= link_to new_project_path, class: "btn btn-default btn-md waves-effect waves-light m-b-30" do %>
          Novo projeto
        <% end %>
        
        <table data-toggle="table"
             data-show-columns="false"
             data-page-size="5"
             data-pagination="true" data-show-pagination-switch="true" class="table-bordered ">
          <thead>
            <tr>
              <th width="100">#</th> 
              <th width="800">Nome</th>
              <th width="800">Empresa</th>
              <th width="800">Contrato</th>
              <th width="200">Patrocinador</th>
              <th width="200">Gerente</th>
              <th width="100">Início</th>
              <th width="200">Término</th>
              <th width="200">Orçamento</th>
              <th width="10" class="last-collumn"></th>
            </tr>
          </thead>
          <tbody>
            <% @projects.each do |project| %>
              <tr>
                <td width="100"><%= project.id.to_s.rjust(3,'0') %></td>
                <td width="800"><%= project.name %></td>
                <td width="800">
                  <% if project.corporation.present? %>
                    <%= project.corporation.name %>
                  <% else %>
                    <%= project.client.name %>
                  <% end %>
                </td>
                <td width="800">Contrato #<%= project.contract_id %></td>
                <td width="800"><%= project.sponsor %></td>
                <td width="800"><%= project.manager %></td>
                <td width="200"><%= project.start_date.strftime("%d/%m/%Y") %></td> 
                <td width="200"><%= project.end_date.strftime("%d/%m/%Y") %></td> 
                <td width="200"><%= number_to_currency(project.estimate, unit: "R$ ", separator: ",", delimiter: ".") %></td>
                <td align="center" class="last-collumn">
                  <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_project_path(project), class: 'btn btn-icon waves-effect waves-light btn-primary btn-xs', title: 'Editar' %>
                  <%= link_to '<i class="fa fa-times"></i>'.html_safe, project, method: :delete, data: { confirm: 'Ao remover uma empresa, registros de projetos e colaboradores vinculados a ela também serão removidos. Confirmar exclusão?' }, class: 'btn btn-icon waves-effect waves-light btn-danger btn-xs', title: 'Excluir' %></td>
              </tr>
            <% end %> 
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% else %>
  <section>
    <div class="container-alt">
      <div class="row">
        <div class="col-sm-12 text-center">
          <div class="home-wrapper">
            <h1 class="home-text text-uppercase"><span class="text-pink"><%= current_user.username %></span></h1>
            <h4 class="text-muted">Antes de criar um projeto, é necessário que se cadastre ao menos uma empresa. Clique abaixo e cadastre uma empresa.</h4>
          </div>
          <div class="row">
            <div class="col-sm-12 text-center">
              <p>
                <%= link_to new_corporation_path, class: "btn btn-default btn-md waves-effect waves-light m-b-30" do %>
                  Nova empresa
                <% end %>
              </p>
            </div> 
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/projects/new.html.erb
<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contract:</strong>
  <%= @project.contract %>
</p>

<p>
  <strong>Area:</strong>
  <%= @project.area %>
</p>

<p>
  <strong>Sponsor:</strong>
  <%= @project.sponsor %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @project.employee %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @project.manager %>
</p>

<p>
  <strong>Objective:</strong>
  <%= @project.objective %>
</p>

<p>
  <strong>Start:</strong>
  <%= @project.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @project.end %>
</p>

<p>
  <strong>Estimate:</strong>
  <%= @project.estimate %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @project.obs %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>