config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :hours
  resources :corporation_types
  resources :corporation_users do
    collection do 
      get :create_corporation_user
      get :delete_corporation_user 
    end
  end 
  resources :process_depts do 
    collection do
      get :create_process
      get :edit_process
      get :delete_process
      get :get_process_by_corporation
      get :get_process_by_client
    end
  end
  resources :appointments do 
    collection do
      post :create_appointment
      post :list_appointment
      post :update_appointment
      post :disable_appointment
      get :register_appointment
      get :delete_appointment
      get :get_appointment
      get :export
    end
  end
  resources :projects do 
    collection do 
      get :get_clients
      get :get_corporations
      get :get_contracts_by_client
      get :get_areas_by_corporation
      get :get_areas_by_client
    end
  end
  resources :contracts
  resources :corporations do 
    collection do 
      get :index_clients
      get :index_companies
      get :get_users_by_corporation
    end
  end
  resources :areas do
    collection do
      get :get_areas_by_corporation
      get :create_area_exist_corporation
      get :get_areas_by_client
      get :create_area
      get :edit_area
      get :delete_area
    end
  end
  # devise_for :users

  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  get 'home/index'
  get 'home/index_company'
  get 'home/information'
  get 'home/not_found'
  get 'home/forbidden'


  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unnaceptable"
  get "/500", to: "errors#internal_error"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    can :read, Corporation, public: true
    can :read, Client, public: true
    can :read, Project, public: true
    can :read, Contract, public: true

    if user.present?  # additional permissions for logged in users (they can read their own posts)
      can [:update, :destroy], Corporation.all.joins(:corporation_users).where("corporation_users.user_id = #{user.id}")
      can [:update, :destroy], Client.find_by_sql("SELECT clients.*
                                  FROM clients
                                  INNER JOIN corporation_users ON corporation_users.corporation_id = clients.corporation_id 
                                  WHERE corporation_users.user_id = #{user.id}")
      can [:update, :destroy], Project.joins("left outer join clients on clients.id = projects.client_id")
                               .where("(projects.corporation_id in (
                                      select corporation_id from corporation_users where user_id = #{user.id})
                                      or
                                      clients.corporation_id in (
                                      select corporation_id from corporation_users where user_id = #{user.id}))")
      can [:update, :destroy], Contract.joins("inner join clients on clients.id = contracts.client_id").where("clients.corporation_id in (select corporation_id from corporation_users where user_id = #{user.id})")
      
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  	belongs_to :user
  	# belongs_to :employee, optional: true
    belongs_to :contract, optional: true
	belongs_to :project, optional: true
end

app/models/area.rb
class Area < ApplicationRecord
   belongs_to :corporation, optional: true
   belongs_to :client, optional: true
   has_many :process_depts, dependent: :destroy
   has_many :projects, dependent: :destroy

   	def self.create_process(params, id)
		params.each do |p|
			unless p.blank?
				ProcessDept.create(:name => p, :area_id => id)
			end 
		end
	end
end

app/models/client.rb
class Client < ApplicationRecord
	belongs_to :corporation
	has_many :contracts, dependent: :destroy
	has_many :projects, dependent: :destroy
end

app/models/contract.rb
class Contract < ApplicationRecord
  # belongs_to :employee, optional: true
  belongs_to :corporation, optional: true
  belongs_to :client
  has_many :appointments, dependent: :destroy
  has_many :projects, dependent: :destroy
end

app/models/corporation.rb
class Corporation < ApplicationRecord
	belongs_to :corporation_type
	has_many :workspace_users, dependent: :destroy
	has_many :areas, dependent: :destroy
	has_many :contracts, dependent: :destroy
	has_many :projects, dependent: :destroy
end

app/models/corporation_area.rb
class CorporationArea < ApplicationRecord
  belongs_to :corporation
  belongs_to :area
end

app/models/hour.rb
class Hour < ApplicationRecord
  belongs_to :corporation
end

app/models/model.rb
class Model < ApplicationRecord
	
end

app/models/process_dept.rb
class ProcessDept < ApplicationRecord
  belongs_to :area

  has_many :appointments, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :contract, optional: true
	belongs_to :corporation, optional: true
	belongs_to :client, optional: true

	has_many :appointments, dependent: :destroy
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_many :appointments
  has_many :corporations, :through => :corporation_users
  has_many :contracts
  has_many :projects
  has_and_belongs_to_many :projects
  
  devise :invitable, :database_authenticatable, :registerable, :invitable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.current=(user)
    Thread.current[:current_user] = user
  end

  def self.current
    Thread.current[:current_user]
  end

end

app/models/workspace.rb
class Workspace < ApplicationRecord
	
end

app/models/workspace_user.rb
class WorkspaceUser < ApplicationRecord
  belongs_to :workspace
  belongs_to :user
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController

 	
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
    def devise_error_messages!
      return "" unless devise_error_messages?
  
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
      sentence = I18n.t("errors.messages.not_saved",
                        :count => resource.errors.count,
                        :resource => resource.class.model_name.human.downcase)
  
      html = <<-HTML
      <div id="error_explanation">
        <h2>#{sentence}</h2>
        <ul>#{messages}</ul>
      </div>
      HTML
  
      html.html_safe
    end
  
    def devise_error_messages?
      !resource.errors.empty?
    end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/users/invitations/edit.html.erb
<div class="account-pages"></div>
<div class="clearfix"></div>
<div class="wrapper-page">
  <div class=" card-box">
    <div class="panel-heading">
      <h3 class="text-center"> Effec<strong class="text-custom">time</strong> </h3>
      <h4 class="text-center"> Finalize seu cadastro</h4>
    </div>

    <div class="panel-body">
    	<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put, :class => 'form-horizontal m-t-20' } do |f| %>

        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
 
        <div class="form-group ">
          <div class="col-xs-12">
            <%= f.text_field :username, :class => "form-control", required:true, placeholder: "Nome de usuário" %>
          </div>
        </div>
 
        <div class="form-group">
          <div class="col-xs-12">
          	<%= f.hidden_field :invitation_token, readonly: true %>
            <%= f.password_field :password, :class => "form-control", autocomplete: "off", placeholder: "Escolha uma senha" %>
            <% if @minimum_password_length %>
              <em>(Mínimo <%= @minimum_password_length %> caracteres)</em>
            <% end %><br />
          </div>
        </div>

        <div class="form-group ">
          <div class="col-xs-12">
            <%= f.password_field :password_confirmation, :class => "form-control", autocomplete: "off", placeholder: "Confirme sua senha" %>
          </div>
        </div>

        <div class="form-group text-center m-t-40">
          <div class="col-xs-12">
            <button class="btn btn-pink btn-block text-uppercase waves-effect waves-light" type="submit">
              Finalizar
            </button>
          </div>
        </div>
 
      <% end %>
    </div>
  </div>

</div>

app/views/users/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <p><%= f.label field %><br />
  <%= f.text_field field %></p>
<% end -%>

  <p><%= f.submit t("devise.invitations.new.submit_button") %></p>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>